create database College;
use College;
create table Student_Details(ID int,Name varchar(10),Address varchar(20) null ,Maths int,Physics int,CS int,Total int);
insert into Student_Details values(1,'Varna','Kozhikode',100,98,96,280);
insert into Student_Details values(2,'Sarang','Kozhikode',94,86,90,280);
insert into Student_Details values(3,'Kim','Kollam',100,100,100,300);
select * from Student_Details;
select id,name from Student_Details;
select * from Student_Details where Address = 'Kozhikode';
update Student_Details set Total = 250 where Name = 'Varna';
delete from Student_Details where Name='Sarang';
insert into Student_Details values(2,'Sarang','Kozhikode',94,86,90,280);
insert into Student_Details values(4,'Anu','Kochi',98,98,99,293);
select * from Student_Details where Address = 'Kollam' or Address = 'Kozhikode';
alter table Student_Details add Department varchar(20);
update Student_Details set Department = 'MCA' where id = 1;
update Student_Details set Department = 'MEC' where id = 2;
update Student_Details set Department = 'CIVIL' where id = 3;
update Student_Details set Department = 'MCA' where id = 4;
select * from Student_Details order by Name;
select * from Student_Details order by ID desc;
alter table Student_Details modify Address varchar(20) null;
insert into Student_Details values(5,'Akash', ,94,86,90,280);
select Name,Address from Student_Details where Address is NULL;
select Name,Total from Student_Details where Total=(select max(Total) from Student_Details);
select Name,Total from Student_Details where Total=(select min(Total) from Student_Details);
insert into Student_Details values(5,'Miya','Kotayam',100,100,90,290,'CIVIL');
select avg(Total) from Student_Details where Department = 'CIVIL';
select sum(Total) from Student_Details where Department = 'MCA';
select Name,Department from Student_Details where Department like 'M%';
select Name,Department from Student_Details where Department like 'C%';
Select Name,Department,Total from Student_Details where Name like'A%';
alter table Student_Details drop Total;
select * from Student_Details;
alter table Student_Details add Total int;
update Student_Details set Total=Maths+Physics+CS where id = 1;
update Student_Details set Total=Maths+Physics+CS where id = 2;
update Student_Details set Total=Maths+Physics+CS where id = 3;
update Student_Details set Total=Maths+Physics+CS where id = 4;
update Student_Details set Total=Maths+Physics+CS where id = 5;
alter table Student_Details add Age int;
update Student_Details set Age=23 where id = 1;
update Student_Details set Age=23 where id = 2;
update Student_Details set Age=22 where id = 3;
update Student_Details set Age=24 where id = 4;
update Student_Details set Age=23 where id = 5;
alter table Student_Details add constraint chk_age check(Age >= 18);
update Student_Details set Age=13 where id = 5;
create table Datatable as select ID,Name,Total from Student_Details where Department = 'MCA';
select * from Datatable;
drop table Datatable;
delete from Student_Details where Age = 24;
select * from Student_Details;
commit;
start transaction;
insert into Student_Details(ID,Name,Address,Maths,Physics,CS,Department,Total,Age) values(4,'Vismaya',null ,94,86,90,'MEC',270,22);
delete from Student_Details where Age = 22;
select * from Student_Details;
rollback;
start transaction;
savepoint Sp2;
update Student_Details set Age = 42 where ID = 4;
select * from Student_Details;
rollback to Sp2;
delete from Student_Details where Name = 'Vismaya';
release savepoint Sp2;
rollback to Sp2;
insert into Student_Details(ID,Name,Address,Maths,Physics,CS,Department,Total,Age) values(3,'Mahesh','Manandavadi' ,100,98,96,'CIVIL',294,23);
select Name from Student_Details where Total=(select max(Total) from Student_Details);
alter table Student_Details add Admission_No int;
update Student_Details set Admission_No = 1001 where ID = 1;
update Student_Details set Admission_No = 1002 where ID = 2;
update Student_Details set Admission_No = 1003 where ID = 3;
update Student_Details set Admission_No = 1004 where ID = 4;
update Student_Details set Admission_No = 1005 where ID = 5;
select * from Student_Details;
alter table Student_Details add column email varchar(30);
update Student_Details set email="varna@gmail.com" where id = 1;
update Student_Details set email="sarang@gmail.com" where id = 2;
update Student_Details set email="sarang@gmail.com" where id = 3;
update Student_Details set email="vismaya@gmail.com" where id = 4;
update Student_Details set email="mahesh@gmail.com" where id = 5;
update Student_Details set email="mariya@gmail.com" where id = 3;
alter table Student_Details add constraint Im_uni unique(Email);
describe Student_Details;

create table depdetail(Dept_ID int, Department varchar(20), teach_id int);
insert into depdetail values(101,"MCA",510); 
select * from depdetail;
start transaction;
savepoint Sp6;
delete from depdetail where Dept_ID = 101;
select * from depdetail;
rollback to Sp6;
select * from depdetail;
commit;
insert into depdetail values(102,"MEC",511); 
insert into depdetail values(101,"CIVIL",512); 
alter table depdetail add constraint prinme primary key(Department);
update depdetail set Dept_ID = 103 where department = "CIVIL";
describe depdetail;
select ID,Department from Student_Details union select Dept_ID,Department from depdetail;